CREATE DATABASE CarRental

CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY,
	CategoryName NVARCHAR(50) UNIQUE NOT NULL, 
	DailyRate DECIMAL(3, 1) NOT NULL, 
	WeeklyRate DECIMAL(3, 1) NOT NULL, 
	MonthlyRate DECIMAL(3, 1) NOT NULL, 
	WeekendRate DECIMAL(3, 1) NOT NULL
)

CREATE TABLE Cars(
	Id INT PRIMARY KEY IDENTITY, 
	PlateNumber NVARCHAR(10) UNIQUE NOT NULL, 
	Manufacturer NVARCHAR(20) NOT NULL, 
	Model NVARCHAR(20) NOT NULL, 
	CarYear DATE NOT NULL, 
	CategoryId INT FOREIGN KEY REFERENCES Categories(Id), 
	Doors INT NOT NULL, 
	Picture VARBINARY, 
	Condition NVARCHAR(200), 
	Available BIT NOT NULL
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY, 
	FirstName NVARCHAR(30) NOT NULL, 
	LastName NVARCHAR(30) NOT NULL, 
	Title NVARCHAR(30), 
	Notes NVARCHAR(MAX)
)